  Documentation:
    Enabled: false

  LineLength:
    Max: 99

  BlockLength:
    Exclude:
      - 'spec/**/*.rb'
      - 'app/admin/*.rb'
  Metrics/AbcSize:
    Exclude:
      - 'app/controllers/users/*.rb'
